version: "3.1"
services:
  web:
    build: .
    ports:
      - 8000:8000
    links: 
      - "db:db"
    depends_on:
      - db
  db:
    image: redis
    restart: always
    volumes:
      - ./docker-data/db-data:/data
    ports:
      - 6379:6379
